---
# tasks file for generate-token

- name: Gerando token worker
  shell:
    kubeadm token create --print-join-command
  register: k8s_token_worker

- name: Adicionando token em dummy host
  add_host:
    name: "K8S_TOKEN_WORKER"
    command: "{{ k8s_token_worker.stdout }}"

- name: debug
  debug:
    msg: "Token para workers --> {{ hostvars['K8S_TOKEN_WORKER']['command'] }}"