- name: Adicionando Repo Docker AlmaLinux
  shell: 
    yum config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Instalando Containerd e demais pacotes
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - containerd.io
    - nfs-utils
    - git
  when: ansible_facts['os_family'] == "RedHat"

- name: Criando diretorio containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Copiando arquivo de configuração containerd
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
  notify:
    - Restart Containerd

- name: Criando arquivo de modulos do containerd
  shell: |
    cat <<EOF | tee /etc/modules-load.d/containerd.conf
    overlay
    br_netfilter
    EOF

- name: Habilitando modulos
  shell:
    modprobe overlay
    modprobe br_netfilter

- name: Adicionando parametros sysctl
  shell: |
    cat <<EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF
  notify:
    - Aplicando sysctl

- name: Adicionando Repo CentOS/RedHat/AlmaLinux
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Instalando os pacotes kubeadm, kubelet e kubectl
  shell:
    yum install -y kubelet-{{ kubernetes_version }} kubeadm-{{ kubernetes_version }} kubectl-{{ kubernetes_version }} --disableexcludes=kubernetes
  notify: 
    - Restart Kubelet
    - Habilitando kubectl
  when: ansible_facts['os_family'] == "RedHat"

- name: Reboot VM
  reboot:
