---
# handlers file for install-k8s

- name: Restart Containerd
  service:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart Kubelet
  service: 
    name: kubelet
    state: restarted

- name: Habilitando kubectl
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes

- name: Aplicando sysctl
  shell:
    sysctl --system