---
# handlers file for install-k8s

- name: Restartando o Docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart Kubelet
  service: 
    name: kubelet
    state: restarted

- name: Habilitando kubectl
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes